# Assignment - 6

## Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
import numpy as np

In [2]:
def func(vec,n,inc):
    if inc == False:
        matx = np.array ([x**(n-i-1) for x in vec for i in range(n)]).reshape(-1,n)
    elif inc == True:
        matx = np.array ([x**i for x in vec for i in range(n)]).reshape(-1,n)
    return matx

In [9]:
input_vec = np.array([1,2,3,4,5])
ncols = 3
matxdec = func(input_vec,ncols,False)
matxinc = func(input_vec,ncols,True)

In [5]:
input_vec

array([1, 2, 3, 4, 5])

In [6]:
ncols

3

In [7]:
matxdec

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [10]:
matxinc

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])